# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.8"

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  - conda install conda-build anaconda-client
  - conda config --set auto_update_conda no
  - conda config --add channels pytorch
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda build conda/clustcr/
  - conda install --use-local clustcr
  - conda info -a

scripts: echo foo
